"""add alert and alert_subscriber tables

Revision ID: 1d7678e78ece
Revises: f532bf462c39
Create Date: 2026-09-16 19:11:50.078976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d7678e78ece'
down_revision: Union[str, Sequence[str], None] = 'f532bf462c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_subscriber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("role IN ('geologist', 'mechanic', 'manager')", name='ck_alert_subscriber_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('ts_detected', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ts_resolved', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.String(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("severity IN ('info', 'warning', 'critical')", name='ck_alert_severity'),
    sa.CheckConstraint("type IN ('well_stopped', 'water_cut_rise', 'gor_rise', 'pressure_anomaly', 'stale_test', 'mtbf_approach', 'production_drop', 'data_gap', 'node_stopped_cascade')", name='ck_alert_type'),
    sa.CheckConstraint('well_id IS NOT NULL OR node_id IS NOT NULL', name='ck_alert_scope'),
    sa.ForeignKeyConstraint(['node_id'], ['gathering_node.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['well.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_node_id_type_active', 'alert', ['node_id', 'type', 'ts_resolved'], unique=False)
    op.create_index('ix_alert_well_id_type_active', 'alert', ['well_id', 'type', 'ts_resolved'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_well_id_type_active', table_name='alert')
    op.drop_index('ix_alert_node_id_type_active', table_name='alert')
    op.drop_table('alert')
    op.drop_table('alert_subscriber')
    # ### end Alembic commands ###
