"""add monthly_production table

Revision ID: 70a31ee88f65
Revises: 78751628ae84
Create Date: 2026-09-17 04:05:43.548215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a31ee88f65'
down_revision: Union[str, Sequence[str], None] = '78751628ae84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_production',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('reservoir_id', sa.Integer(), nullable=True),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('calendar_days', sa.Integer(), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=False),
    sa.Column('q_oil_t', sa.Float(), nullable=False),
    sa.Column('q_water_t', sa.Float(), nullable=False),
    sa.Column('q_gas_m3', sa.Float(), nullable=True),
    sa.Column('q_liquid_t', sa.Float(), nullable=False),
    sa.Column('gor', sa.Float(), nullable=True),
    sa.Column('water_cut_pct', sa.Float(), nullable=True),
    sa.Column('q_oil_rate_t_d', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.CheckConstraint('calendar_days BETWEEN 1 AND 31', name='ck_monthly_production_calendar_days_range'),
    sa.ForeignKeyConstraint(['reservoir_id'], ['reservoir.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['well.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('well_id', 'period_month', name='uq_monthly_production_well_month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthly_production')
    # ### end Alembic commands ###
