"""add oil_density_t_m3 to reservoir

Revision ID: 72f01ed19544
Revises: 70a31ee88f65
Create Date: 2026-09-17 04:54:08.827711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f01ed19544'
down_revision: Union[str, Sequence[str], None] = '70a31ee88f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservoir', sa.Column('oil_density_t_m3', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservoir', 'oil_density_t_m3')
    # ### end Alembic commands ###
