"""add ingestion_run and ingestion_quarantine tables

Revision ID: 7cc89f9232e6
Revises: c871f01a546d
Create Date: 2026-09-16 12:17:37.582009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cc89f9232e6'
down_revision: Union[str, Sequence[str], None] = 'c871f01a546d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('period_label', sa.String(), nullable=True),
    sa.Column('source_path', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('records_read', sa.Integer(), nullable=False),
    sa.Column('records_loaded', sa.Integer(), nullable=False),
    sa.Column('records_quarantined', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("source IN ('csv', 'synthetic', 'opcua')", name='ck_ingestion_run_source'),
    sa.CheckConstraint("status IN ('running', 'success', 'partial', 'failed')", name='ck_ingestion_run_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_quarantine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('reason_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("reason IN ('unknown_well', 'parse_error', 'unit_conversion_error', 'schema_mismatch', 'invalid_value')", name='ck_ingestion_quarantine_reason'),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_quarantine_reason', 'ingestion_quarantine', ['reason'], unique=False)
    op.create_index('ix_ingestion_quarantine_run_id', 'ingestion_quarantine', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingestion_quarantine_run_id', table_name='ingestion_quarantine')
    op.drop_index('ix_ingestion_quarantine_reason', table_name='ingestion_quarantine')
    op.drop_table('ingestion_quarantine')
    op.drop_table('ingestion_run')
    # ### end Alembic commands ###
