"""create master data, reference and timeseries tables

Revision ID: af0d9a143175
Revises: 
Create Date: 2026-09-16 11:30:43.872280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af0d9a143175'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downtime_reason',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['downtime_reason.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('field_type', sa.String(), nullable=False),
    sa.CheckConstraint("field_type IN ('oil', 'gas', 'gas_condensate')", name='ck_field_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gtm_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('measurement_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('gathering_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.CheckConstraint("node_type IN ('gu', 'dns', 'agzu')", name='ck_gathering_node_type'),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_id', 'name', name='uq_gathering_node_field_name')
    )
    op.create_table('reservoir',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('horizon_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_id', 'name', name='uq_reservoir_field_name')
    )
    op.create_table('well',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uwi', sa.String(), nullable=False),
    sa.Column('gos_number', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('well_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('spud_date', sa.Date(), nullable=True),
    sa.Column('wellhead_x', sa.Float(), nullable=True),
    sa.Column('wellhead_y', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.CheckConstraint("status IN ('active', 'idle', 'mothballed', 'abandoned', 'drilling')", name='ck_well_status'),
    sa.CheckConstraint("well_type IN ('producer', 'injector', 'piezometric', 'water_intake')", name='ck_well_type'),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uwi')
    )
    op.create_table('completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('reservoir_id', sa.Integer(), nullable=False),
    sa.Column('top_md', sa.Float(), nullable=False),
    sa.Column('bottom_md', sa.Float(), nullable=False),
    sa.Column('perf_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint("status IN ('open', 'isolated', 'closed')", name='ck_completion_status'),
    sa.CheckConstraint('bottom_md > top_md', name='ck_completion_bottom_gt_top'),
    sa.ForeignKeyConstraint(['reservoir_id'], ['reservoir.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['well.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_completion_well_id', 'completion', ['well_id'], unique=False)
    op.create_table('daily_production',
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('q_oil_t', sa.Float(), nullable=False),
    sa.Column('q_liquid_t', sa.Float(), nullable=False),
    sa.Column('q_water_m3', sa.Float(), nullable=False),
    sa.Column('q_gas_m3', sa.Float(), nullable=True),
    sa.Column('hours_on', sa.Float(), nullable=False),
    sa.Column('ke', sa.Float(), nullable=False),
    sa.Column('allocation_factor', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.CheckConstraint('hours_on BETWEEN 0 AND 24', name='ck_daily_production_hours_on_range'),
    sa.CheckConstraint('ke BETWEEN 0 AND 1', name='ck_daily_production_ke_range'),
    sa.CheckConstraint('q_gas_m3 IS NULL OR q_gas_m3 >= 0', name='ck_daily_production_q_gas_nonneg'),
    sa.CheckConstraint('q_liquid_t >= 0', name='ck_daily_production_q_liquid_nonneg'),
    sa.CheckConstraint('q_oil_t >= 0', name='ck_daily_production_q_oil_nonneg'),
    sa.CheckConstraint('q_water_m3 >= 0', name='ck_daily_production_q_water_nonneg'),
    sa.ForeignKeyConstraint(['well_id'], ['well.id'], ),
    sa.PrimaryKeyConstraint('well_id', 'date')
    )
    op.create_table('downtime',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('ts_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ts_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('deferred_oil_t', sa.Float(), nullable=True),
    sa.Column('is_planned', sa.Boolean(), nullable=False),
    sa.CheckConstraint('deferred_oil_t IS NULL OR deferred_oil_t >= 0', name='ck_downtime_deferred_oil_nonneg'),
    sa.CheckConstraint('ts_end > ts_start', name='ck_downtime_period'),
    sa.ForeignKeyConstraint(['reason_id'], ['downtime_reason.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['well.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_downtime_well_id_ts_start', 'downtime', ['well_id', 'ts_start'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('equipment_type', sa.String(), nullable=False),
    sa.Column('type_size', sa.String(), nullable=True),
    sa.Column('run_depth', sa.Float(), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=False),
    sa.Column('pull_date', sa.Date(), nullable=True),
    sa.CheckConstraint("equipment_type IN ('esp', 'srp', 'flowing', 'gas_lift')", name='ck_equipment_type'),
    sa.CheckConstraint('pull_date IS NULL OR pull_date > install_date', name='ck_equipment_pull_after_install'),
    sa.ForeignKeyConstraint(['well_id'], ['well.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_equipment_well_id', 'equipment', ['well_id'], unique=False)
    op.create_table('gtm_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('gtm_type_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effect_fact_t', sa.Float(), nullable=True),
    sa.Column('effect_plan_t', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['gtm_type_id'], ['gtm_type.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['well.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gtm_event_well_id_event_date', 'gtm_event', ['well_id', 'event_date'], unique=False)
    op.create_table('lab_analysis',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('analysis_type', sa.String(), nullable=False),
    sa.Column('water_cut_pct', sa.Float(), nullable=True),
    sa.Column('density_kg_m3', sa.Float(), nullable=True),
    sa.Column('viscosity_cst', sa.Float(), nullable=True),
    sa.Column('gas_composition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lab_name', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.CheckConstraint("analysis_type IN ('water_cut', 'density', 'viscosity', 'gas_composition')", name='ck_lab_analysis_type'),
    sa.CheckConstraint('density_kg_m3 IS NULL OR density_kg_m3 >= 0', name='ck_lab_analysis_density_nonneg'),
    sa.CheckConstraint('viscosity_cst IS NULL OR viscosity_cst >= 0', name='ck_lab_analysis_viscosity_nonneg'),
    sa.CheckConstraint('water_cut_pct IS NULL OR water_cut_pct BETWEEN 0 AND 100', name='ck_lab_analysis_water_cut_range'),
    sa.ForeignKeyConstraint(['well_id'], ['well.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lab_analysis_well_id_ts', 'lab_analysis', ['well_id', 'ts'], unique=False)
    op.create_table('measurement',
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('quality', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.CheckConstraint("quality IN ('good', 'suspect', 'bad')", name='ck_measurement_quality'),
    sa.ForeignKeyConstraint(['tag_id'], ['measurement_tag.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['well.id'], ),
    sa.PrimaryKeyConstraint('well_id', 'ts', 'tag_id')
    )
    op.create_table('node_production',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('q_oil_t', sa.Float(), nullable=False),
    sa.Column('q_liquid_t', sa.Float(), nullable=False),
    sa.Column('q_water_m3', sa.Float(), nullable=False),
    sa.Column('q_gas_m3', sa.Float(), nullable=True),
    sa.CheckConstraint('q_gas_m3 IS NULL OR q_gas_m3 >= 0', name='ck_node_production_q_gas_nonneg'),
    sa.CheckConstraint('q_liquid_t >= 0', name='ck_node_production_q_liquid_nonneg'),
    sa.CheckConstraint('q_oil_t >= 0', name='ck_node_production_q_oil_nonneg'),
    sa.CheckConstraint('q_water_m3 >= 0', name='ck_node_production_q_water_nonneg'),
    sa.ForeignKeyConstraint(['node_id'], ['gathering_node.id'], ),
    sa.PrimaryKeyConstraint('node_id', 'date')
    )
    op.create_table('well_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('external_system', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['well_id'], ['well.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_system', 'external_id', name='uq_well_alias_external')
    )
    op.create_index('ix_well_alias_well_id', 'well_alias', ['well_id'], unique=False)
    op.create_table('well_gathering_node_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name='ck_well_gathering_node_history_period'),
    sa.ForeignKeyConstraint(['node_id'], ['gathering_node.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['well.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_well_gathering_node_history_well_id', 'well_gathering_node_history', ['well_id', 'valid_from'], unique=False)
    op.create_table('well_test',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('ts_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ts_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_h', sa.Float(), nullable=False),
    sa.Column('q_liquid', sa.Float(), nullable=False),
    sa.Column('q_oil', sa.Float(), nullable=False),
    sa.Column('q_water', sa.Float(), nullable=False),
    sa.Column('q_gas', sa.Float(), nullable=True),
    sa.Column('water_cut', sa.Float(), nullable=True),
    sa.Column('gor', sa.Float(), nullable=True),
    sa.Column('p_buf', sa.Float(), nullable=True),
    sa.Column('p_zatr', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.CheckConstraint('gor IS NULL OR gor >= 0', name='ck_well_test_gor_nonneg'),
    sa.CheckConstraint('q_gas IS NULL OR q_gas >= 0', name='ck_well_test_q_gas_nonneg'),
    sa.CheckConstraint('q_liquid >= 0', name='ck_well_test_q_liquid_nonneg'),
    sa.CheckConstraint('q_oil >= 0', name='ck_well_test_q_oil_nonneg'),
    sa.CheckConstraint('q_water >= 0', name='ck_well_test_q_water_nonneg'),
    sa.CheckConstraint('ts_end > ts_start', name='ck_well_test_period'),
    sa.CheckConstraint('water_cut IS NULL OR water_cut BETWEEN 0 AND 100', name='ck_well_test_water_cut_range'),
    sa.ForeignKeyConstraint(['well_id'], ['well.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_well_test_well_id_ts_start', 'well_test', ['well_id', 'ts_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_well_test_well_id_ts_start', table_name='well_test')
    op.drop_table('well_test')
    op.drop_index('ix_well_gathering_node_history_well_id', table_name='well_gathering_node_history')
    op.drop_table('well_gathering_node_history')
    op.drop_index('ix_well_alias_well_id', table_name='well_alias')
    op.drop_table('well_alias')
    op.drop_table('node_production')
    op.drop_table('measurement')
    op.drop_index('ix_lab_analysis_well_id_ts', table_name='lab_analysis')
    op.drop_table('lab_analysis')
    op.drop_index('ix_gtm_event_well_id_event_date', table_name='gtm_event')
    op.drop_table('gtm_event')
    op.drop_index('ix_equipment_well_id', table_name='equipment')
    op.drop_table('equipment')
    op.drop_index('ix_downtime_well_id_ts_start', table_name='downtime')
    op.drop_table('downtime')
    op.drop_table('daily_production')
    op.drop_index('ix_completion_well_id', table_name='completion')
    op.drop_table('completion')
    op.drop_table('well')
    op.drop_table('reservoir')
    op.drop_table('gathering_node')
    op.drop_table('measurement_tag')
    op.drop_table('gtm_type')
    op.drop_table('field')
    op.drop_table('downtime_reason')
    # ### end Alembic commands ###
