"""add water_density_t_m3 and density_confirmed to reservoir

Revision ID: ee1a92606236
Revises: 72f01ed19544
Create Date: 2026-09-17 19:25:49.712705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee1a92606236'
down_revision: Union[str, Sequence[str], None] = '72f01ed19544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservoir', sa.Column('water_density_t_m3', sa.Float(), nullable=True))
    op.add_column(
        'reservoir', sa.Column('density_confirmed', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservoir', 'density_confirmed')
    op.drop_column('reservoir', 'water_density_t_m3')
    # ### end Alembic commands ###
