"""add deferred_production table

Revision ID: f532bf462c39
Revises: 98ac2912cfae
Create Date: 2026-09-16 18:44:35.594097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f532bf462c39'
down_revision: Union[str, Sequence[str], None] = '98ac2912cfae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deferred_production',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('reason_id', sa.Integer(), nullable=True),
    sa.Column('volume_oil_t', sa.Float(), nullable=False),
    sa.Column('potential_basis', sa.String(), nullable=False),
    sa.CheckConstraint("(category = 'downtime') = (reason_id IS NOT NULL)", name='ck_deferred_production_reason_matches_category'),
    sa.CheckConstraint("category IN ('downtime', 'rate_reduction', 'watering', 'idle_fund')", name='ck_deferred_production_category'),
    sa.CheckConstraint("potential_basis IN ('last_valid_test', 'decline_trend', 'model_forecast')", name='ck_deferred_production_basis'),
    sa.CheckConstraint('volume_oil_t >= 0', name='ck_deferred_production_volume_nonneg'),
    sa.ForeignKeyConstraint(['reason_id'], ['downtime_reason.id'], ),
    sa.ForeignKeyConstraint(['well_id'], ['well.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deferred_production_well_id_date', 'deferred_production', ['well_id', 'date'], unique=False)
    op.create_index('uq_deferred_production_downtime', 'deferred_production', ['well_id', 'date', 'category', 'reason_id'], unique=True, postgresql_where=sa.text('reason_id IS NOT NULL'))
    op.create_index('uq_deferred_production_non_downtime', 'deferred_production', ['well_id', 'date', 'category'], unique=True, postgresql_where=sa.text('reason_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_deferred_production_non_downtime', table_name='deferred_production', postgresql_where=sa.text('reason_id IS NULL'))
    op.drop_index('uq_deferred_production_downtime', table_name='deferred_production', postgresql_where=sa.text('reason_id IS NOT NULL'))
    op.drop_index('ix_deferred_production_well_id_date', table_name='deferred_production')
    op.drop_table('deferred_production')
    # ### end Alembic commands ###
